name: hron
description: Human-readable cron â€” scheduling expressions that are a superset of what cron can express.
version: 0.6.1
repository: https://github.com/prasrvenkat/hron
homepage: https://github.com/prasrvenkat/hron
topics:
  - cron
  - scheduler
  - scheduling
  - human-readable
  - hron

environment:
  sdk: ^3.11.0

dependencies:
  timezone: ^0.11.0

dev_dependencies:
  test: ^1.25.0
  path: ^1.9.0
  lints: ^6.0.0
