name: Dart

on:
  push:
    branches: [main]
    paths:
      - "dart/**"
      - "spec/**"
  pull_request:
    paths:
      - "dart/**"
      - "spec/**"

jobs:
  format:
    name: Format & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          install_args: dart just
      - name: Install dependencies
        run: dart pub get
        working-directory: dart
      - name: Format & Lint
        run: just lint-dart

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          install_args: dart just
      - name: Test
        run: just test-dart
