name: Ruby

on:
  push:
    branches: [main]
    paths: ["ruby/**", "spec/**"]
  pull_request:
    paths: ["ruby/**", "spec/**"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          install_args: ruby
      - name: Install dependencies
        run: bundle install
        working-directory: ruby
      - name: Run tests
        run: bundle exec rake test
        working-directory: ruby

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          install_args: ruby
      - name: Install dependencies
        run: bundle install
        working-directory: ruby
      - name: Run Standard
        run: bundle exec standardrb
        working-directory: ruby
