name: Ruby

on:
  push:
    branches: [main]
    paths: ["ruby/**", "spec/**"]
  pull_request:
    paths: ["ruby/**", "spec/**"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          install_args: ruby just
      - name: Test
        run: just test-ruby

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          install_args: ruby just
      - name: Install dependencies
        run: bundle install
        working-directory: ruby
      - name: Lint
        run: just lint-ruby
