name: TypeScript

on:
  push:
    branches: [main]
    paths:
      - "ts/**"
      - "spec/**"
  pull_request:
    paths:
      - "ts/**"
      - "spec/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        with:
          install_args: nodejs pnpm

      - name: Install dependencies
        run: cd ts && pnpm install --frozen-lockfile

      - name: Lint & Format
        run: cd ts && pnpm lint

      - name: Typecheck
        run: cd ts && pnpm typecheck

      - name: Test
        run: cd ts && pnpm test

      - name: Build
        run: cd ts && pnpm build
